targets:
  $default:
    builders:
      fcheck|version_builder:
        generate_for:
          - pubspec.yaml

builders:
  version_builder:
    import: "tool/version_builder.dart"
    builder_factories: ["versionBuilder"]
    build_extensions: {"$package$": ["lib/src/version.dart"]}
    auto_apply: root_package
    build_to: source
