graph TD
    subgraph Layer_5["Layer 5"]
        src_layers_layers_issue["src/layers/layers_issue.dart\n↓3 ↑0"]
        src_hardcoded_strings_hardcoded_string_issue["src/hardcoded_strings/hardcoded_string_issue.dart\n↓3 ↑0"]
        src_magic_numbers_magic_number_issue["src/magic_numbers/magic_number_issue.dart\n↓3 ↑0"]
        src_sort_sort_analyzer["src/sort/sort_analyzer.dart\n↓1 ↑4"]
    end
    subgraph Layer_4["Layer 4"]
        src_layers_layers_results["src/layers/layers_results.dart\n↓7 ↑1"]
        src_graphs_badge_model["src/graphs/badge_model.dart\n↓3 ↑0"]
        src_metrics_file_metrics["src/metrics/file_metrics.dart\n↓2 ↑0"]
        src_hardcoded_strings_hardcoded_string_visitor["src/hardcoded_strings/hardcoded_string_visitor.dart\n↓1 ↑1"]
        src_layers_layers_visitor["src/layers/layers_visitor.dart\n↓1 ↑0"]
        src_magic_numbers_magic_number_visitor["src/magic_numbers/magic_number_visitor.dart\n↓1 ↑1"]
        src_sort_sort["src/sort/sort.dart\n↓2 ↑4"]
    end
    subgraph Layer_3["Layer 3"]
        src_graphs_graph_format_utils["src/graphs/graph_format_utils.dart\n↓2 ↑1"]
        src_graphs_svg_common["src/graphs/svg_common.dart\n↓2 ↑1"]
        src_graphs_svg_styles["src/graphs/svg_styles.dart\n↓2 ↑0"]
        src_models_rect["src/models/rect.dart\n↓1 ↑0"]
        src_hardcoded_strings_hardcoded_string_analyzer["src/hardcoded_strings/hardcoded_string_analyzer.dart\n↓1 ↑3"]
        src_layers_layers_analyzer["src/layers/layers_analyzer.dart\n↓1 ↑4"]
        src_magic_numbers_magic_number_analyzer["src/magic_numbers/magic_number_analyzer.dart\n↓1 ↑3"]
        src_metrics_project_metrics["src/metrics/project_metrics.dart\n↓1 ↑5"]
    end
    subgraph Layer_2["Layer 2"]
        src_graphs_export_mermaid["src/graphs/export_mermaid.dart\n↓1 ↑2"]
        src_graphs_export_plantuml["src/graphs/export_plantuml.dart\n↓1 ↑2"]
        src_graphs_export_svg["src/graphs/export_svg.dart\n↓1 ↑4"]
        src_graphs_export_svg_folders["src/graphs/export_svg_folders.dart\n↓1 ↑5"]
        fcheck["fcheck.dart\n↓1 ↑8"]
        src_models_version["src/models/version.dart\n↓1 ↑0"]
    end
    subgraph Layer_6["Layer 6"]
        src_models_file_utils["src/models/file_utils.dart\n↓5 ↑0"]
        src_models_class_visitor["src/models/class_visitor.dart\n↓2 ↑0"]
        src_sort_sort_members["src/sort/sort_members.dart\n↓2 ↑0"]
        src_sort_sort_issue["src/sort/sort_issue.dart\n↓2 ↑0"]
    end
    subgraph Layer_1["Layer 1"]
        ._bin_fcheck["./bin/fcheck.dart\n↓0 ↑6"]
    end
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/src/graphs/export_mermaid.dart| src_graphs_export_mermaid
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/src/graphs/export_plantuml.dart| src_graphs_export_plantuml
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/src/graphs/export_svg.dart| src_graphs_export_svg
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/src/graphs/export_svg_folders.dart| src_graphs_export_svg_folders
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/fcheck.dart| fcheck
    ._bin_fcheck -->|./bin/fcheck.dart > ./lib/src/models/version.dart| src_models_version
    fcheck -->|./lib/fcheck.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    fcheck -->|./lib/fcheck.dart > ./lib/src/metrics/file_metrics.dart| src_metrics_file_metrics
    fcheck -->|./lib/fcheck.dart > ./lib/src/hardcoded_strings/hardcoded_string_analyzer.dart| src_hardcoded_strings_hardcoded_string_analyzer
    fcheck -->|./lib/fcheck.dart > ./lib/src/layers/layers_analyzer.dart| src_layers_layers_analyzer
    fcheck -->|./lib/fcheck.dart > ./lib/src/magic_numbers/magic_number_analyzer.dart| src_magic_numbers_magic_number_analyzer
    fcheck -->|./lib/fcheck.dart > ./lib/src/sort/sort.dart| src_sort_sort
    fcheck -->|./lib/fcheck.dart > ./lib/src/metrics/project_metrics.dart| src_metrics_project_metrics
    fcheck -->|./lib/fcheck.dart > ./lib/src/models/file_utils.dart| src_models_file_utils
    src_metrics_project_metrics -->|./lib/src/metrics/project_metrics.dart > ./lib/src/hardcoded_strings/hardcoded_string_issue.dart| src_hardcoded_strings_hardcoded_string_issue
    src_metrics_project_metrics -->|./lib/src/metrics/project_metrics.dart > ./lib/src/layers/layers_issue.dart| src_layers_layers_issue
    src_metrics_project_metrics -->|./lib/src/metrics/project_metrics.dart > ./lib/src/metrics/file_metrics.dart| src_metrics_file_metrics
    src_metrics_project_metrics -->|./lib/src/metrics/project_metrics.dart > ./lib/src/magic_numbers/magic_number_issue.dart| src_magic_numbers_magic_number_issue
    src_metrics_project_metrics -->|./lib/src/metrics/project_metrics.dart > ./lib/src/sort/sort.dart| src_sort_sort
    src_hardcoded_strings_hardcoded_string_visitor -->|./lib/src/hardcoded_strings/hardcoded_string_visitor.dart > ./lib/src/hardcoded_strings/hardcoded_string_issue.dart| src_hardcoded_strings_hardcoded_string_issue
    src_hardcoded_strings_hardcoded_string_analyzer -->|./lib/src/hardcoded_strings/hardcoded_string_analyzer.dart > ./lib/src/hardcoded_strings/hardcoded_string_issue.dart| src_hardcoded_strings_hardcoded_string_issue
    src_hardcoded_strings_hardcoded_string_analyzer -->|./lib/src/hardcoded_strings/hardcoded_string_analyzer.dart > ./lib/src/hardcoded_strings/hardcoded_string_visitor.dart| src_hardcoded_strings_hardcoded_string_visitor
    src_hardcoded_strings_hardcoded_string_analyzer -->|./lib/src/hardcoded_strings/hardcoded_string_analyzer.dart > ./lib/src/models/file_utils.dart| src_models_file_utils
    src_layers_layers_results -->|./lib/src/layers/layers_results.dart > ./lib/src/layers/layers_issue.dart| src_layers_layers_issue
    src_layers_layers_analyzer -->|./lib/src/layers/layers_analyzer.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    src_layers_layers_analyzer -->|./lib/src/layers/layers_analyzer.dart > ./lib/src/models/file_utils.dart| src_models_file_utils
    src_layers_layers_analyzer -->|./lib/src/layers/layers_analyzer.dart > ./lib/src/layers/layers_issue.dart| src_layers_layers_issue
    src_layers_layers_analyzer -->|./lib/src/layers/layers_analyzer.dart > ./lib/src/layers/layers_visitor.dart| src_layers_layers_visitor
    src_sort_sort -->|./lib/src/sort/sort.dart > ./lib/src/models/class_visitor.dart| src_models_class_visitor
    src_sort_sort -->|./lib/src/sort/sort.dart > ./lib/src/sort/sort_members.dart| src_sort_sort_members
    src_sort_sort -->|./lib/src/sort/sort.dart > ./lib/src/sort/sort_analyzer.dart| src_sort_sort_analyzer
    src_sort_sort -->|./lib/src/sort/sort.dart > ./lib/src/sort/sort_issue.dart| src_sort_sort_issue
    src_sort_sort_analyzer -->|./lib/src/sort/sort_analyzer.dart > ./lib/src/models/class_visitor.dart| src_models_class_visitor
    src_sort_sort_analyzer -->|./lib/src/sort/sort_analyzer.dart > ./lib/src/sort/sort_members.dart| src_sort_sort_members
    src_sort_sort_analyzer -->|./lib/src/sort/sort_analyzer.dart > ./lib/src/sort/sort_issue.dart| src_sort_sort_issue
    src_sort_sort_analyzer -->|./lib/src/sort/sort_analyzer.dart > ./lib/src/models/file_utils.dart| src_models_file_utils
    src_magic_numbers_magic_number_visitor -->|./lib/src/magic_numbers/magic_number_visitor.dart > ./lib/src/magic_numbers/magic_number_issue.dart| src_magic_numbers_magic_number_issue
    src_magic_numbers_magic_number_analyzer -->|./lib/src/magic_numbers/magic_number_analyzer.dart > ./lib/src/magic_numbers/magic_number_issue.dart| src_magic_numbers_magic_number_issue
    src_magic_numbers_magic_number_analyzer -->|./lib/src/magic_numbers/magic_number_analyzer.dart > ./lib/src/magic_numbers/magic_number_visitor.dart| src_magic_numbers_magic_number_visitor
    src_magic_numbers_magic_number_analyzer -->|./lib/src/magic_numbers/magic_number_analyzer.dart > ./lib/src/models/file_utils.dart| src_models_file_utils
    src_graphs_graph_format_utils -->|./lib/src/graphs/graph_format_utils.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    src_graphs_svg_common -->|./lib/src/graphs/svg_common.dart > ./lib/src/graphs/badge_model.dart| src_graphs_badge_model
    src_graphs_export_plantuml -->|./lib/src/graphs/export_plantuml.dart > ./lib/src/graphs/graph_format_utils.dart| src_graphs_graph_format_utils
    src_graphs_export_plantuml -->|./lib/src/graphs/export_plantuml.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    src_graphs_export_svg_folders -->|./lib/src/graphs/export_svg_folders.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    src_graphs_export_svg_folders -->|./lib/src/graphs/export_svg_folders.dart > ./lib/src/models/rect.dart| src_models_rect
    src_graphs_export_svg_folders -->|./lib/src/graphs/export_svg_folders.dart > ./lib/src/graphs/svg_common.dart| src_graphs_svg_common
    src_graphs_export_svg_folders -->|./lib/src/graphs/export_svg_folders.dart > ./lib/src/graphs/svg_styles.dart| src_graphs_svg_styles
    src_graphs_export_svg_folders -->|./lib/src/graphs/export_svg_folders.dart > ./lib/src/graphs/badge_model.dart| src_graphs_badge_model
    src_graphs_export_svg -->|./lib/src/graphs/export_svg.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
    src_graphs_export_svg -->|./lib/src/graphs/export_svg.dart > ./lib/src/graphs/svg_common.dart| src_graphs_svg_common
    src_graphs_export_svg -->|./lib/src/graphs/export_svg.dart > ./lib/src/graphs/svg_styles.dart| src_graphs_svg_styles
    src_graphs_export_svg -->|./lib/src/graphs/export_svg.dart > ./lib/src/graphs/badge_model.dart| src_graphs_badge_model
    src_graphs_export_mermaid -->|./lib/src/graphs/export_mermaid.dart > ./lib/src/graphs/graph_format_utils.dart| src_graphs_graph_format_utils
    src_graphs_export_mermaid -->|./lib/src/graphs/export_mermaid.dart > ./lib/src/layers/layers_results.dart| src_layers_layers_results
